-- H2 Database Schema for Testing

CREATE TABLE IF NOT EXISTS DELIVERY (
    DELIVERY_ID BIGINT NOT NULL,
    STATUS VARCHAR(10),
    CITY VARCHAR(100),
    STREET VARCHAR(200),
    ZIPCODE VARCHAR(20),
    CONSTRAINT DELIVERY_PK PRIMARY KEY (DELIVERY_ID)
);

CREATE TABLE IF NOT EXISTS ITEM (
    ITEM_ID BIGINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    PRICE INTEGER,
    STOCK_QUANTITY INTEGER,
    DTYPE VARCHAR(20),
    AUTHOR VARCHAR(200),
    ISBN VARCHAR(50),
    DIRECTOR VARCHAR(200),
    ACTOR VARCHAR(200),
    ARTIST VARCHAR(200),
    ETC VARCHAR(500),
    CONSTRAINT CK_ITEM_DTYPE CHECK (DTYPE IN ('BOOK', 'MOVIE', 'ALBUM')),
    CONSTRAINT CK_ITEM_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CK_ITEM_STOCK CHECK (STOCK_QUANTITY >= 0),
    CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID BIGINT NOT NULL,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    STREET VARCHAR(200),
    ZIPCODE VARCHAR(20),
    CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT NOT NULL,
    MEMBER_ID BIGINT,
    DELIVERY_ID BIGINT,
    ORDERDATE TIMESTAMP,
    STATUS VARCHAR(10),
    CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY(DELIVERY_ID),
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDER_ITEM_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    ORDERPRICE INTEGER,
    COUNT INTEGER,
    CONSTRAINT PK_ORDERITEM PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDERITEM_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT FK_ORDERITEM_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Sequences
CREATE SEQUENCE IF NOT EXISTS ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS MEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS DELIVERY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDER_ITEM_SEQ START WITH 1 INCREMENT BY 1;
